<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="preload" href="/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2" as="font" crossorigin="" type="font/woff2"/>
        <link rel="preload" as="image" href="/CATRAH.png"/>
        <link rel="stylesheet" href="/_next/static/css/7deefefba10c4824.css" data-precedence="next"/>
        <link rel="stylesheet" href="/_next/static/css/4282badd3d75c77e.css" data-precedence="next"/>
        <link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/webpack-b228ec7a07a7d629.js"/>
        <script src="/_next/static/chunks/fd9d1056-2821b0f0cabcd8bd.js" async=""></script>
        <script src="/_next/static/chunks/23-ef3c75ca91144cad.js" async=""></script>
        <script src="/_next/static/chunks/main-app-f73cdb3bce740b12.js" async=""></script>
        <script src="/_next/static/chunks/231-bea070b1ecddfbbc.js" async=""></script>
        <script src="/_next/static/chunks/app/page-9099bcd4aeeeddcf.js" async=""></script>
        <title>Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16"/>
        <meta name="next-size-adjust"/>
        <script src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js" noModule=""></script>
    </head>
    <body class="__className_aaf875">
        <div class="page_container__jZF7q">
            <img src="/CATRAH.png" alt="Logo" class="page_logo__ikIZE"/>
            <div class="page_description__lvaOp">Catrah merupakan aplikasi Catatan Transaksi Harian yang dirancang khusus untuk membantu pengguna mancatat transaksi harian dengan mudah dan efisien.</div>
            <a href="/halaman">
                <div class="page_startButton__monj7">Gunakan Sekarang!!</div>
            </a>
        </div>
        <script src="/_next/static/chunks/webpack-b228ec7a07a7d629.js" async=""></script>
        <script>
            (self.__next_f = self.__next_f || []).push([0]);
            self.__next_f.push([2, null])
        </script>
        <script>
            self.__next_f.push([1, "1:HL[\"/_next/static/media/c9a5bc6a7c948fb0-s.p.woff2\",\"font\",{\"crossOrigin\":\"\",\"type\":\"font/woff2\"}]\n2:HL[\"/_next/static/css/7deefefba10c4824.css\",\"style\"]\n3:HL[\"/_next/static/css/4282badd3d75c77e.css\",\"style\"]\n"])
        </script>
        <script>
            self.__next_f.push([1, "4:I[5751,[],\"\"]\n6:I[231,[\"231\",\"static/chunks/231-bea070b1ecddfbbc.js\",\"931\",\"static/chunks/app/page-9099bcd4aeeeddcf.js\"],\"\"]\n7:I[9275,[],\"\"]\n8:I[1343,[],\"\"]\na:I[6130,[],\"\"]\nb:[]\n"])
        </script>
        <script>
            self.__next_f.push([1, "0:[[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/7deefefba10c4824.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]],[\"$\",\"$L4\",null,{\"buildId\":\"3DKiSrkr9IC9wRrkA9VNu\",\"assetPrefix\":\"\",\"initialCanonicalUrl\":\"/\",\"initialTree\":[\"\",{\"children\":[\"__PAGE__\",{}]},\"$undefined\",\"$undefined\",true],\"initialSeedData\":[\"\",{\"children\":[\"__PAGE__\",{},[[\"$L5\",[\"$\",\"div\",null,{\"className\":\"page_container__jZF7q\",\"children\":[[\"$\",\"img\",null,{\"src\":\"/CATRAH.png\",\"alt\":\"Logo\",\"className\":\"page_logo__ikIZE\"}],[\"$\",\"div\",null,{\"className\":\"page_description__lvaOp\",\"children\":\"Catrah merupakan aplikasi Catatan Transaksi Harian yang dirancang khusus untuk membantu pengguna mancatat transaksi harian dengan mudah dan efisien.\"}],[\"$\",\"$L6\",null,{\"href\":\"/halaman\",\"children\":[\"$\",\"div\",null,{\"className\":\"page_startButton__monj7\",\"children\":\"Gunakan Sekarang!!\"}]}]]}]],null],null]},[[\"$\",\"html\",null,{\"lang\":\"en\",\"children\":[\"$\",\"body\",null,{\"className\":\"__className_aaf875\",\"children\":[\"$\",\"$L7\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$L8\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":[[\"$\",\"title\",null,{\"children\":\"404: This page could not be found.\"}],[\"$\",\"div\",null,{\"style\":{\"fontFamily\":\"system-ui,\\\"Segoe UI\\\",Roboto,Helvetica,Arial,sans-serif,\\\"Apple Color Emoji\\\",\\\"Segoe UI Emoji\\\"\",\"height\":\"100vh\",\"textAlign\":\"center\",\"display\":\"flex\",\"flexDirection\":\"column\",\"alignItems\":\"center\",\"justifyContent\":\"center\"},\"children\":[\"$\",\"div\",null,{\"children\":[[\"$\",\"style\",null,{\"dangerouslySetInnerHTML\":{\"__html\":\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\"}}],[\"$\",\"h1\",null,{\"className\":\"next-error-h1\",\"style\":{\"display\":\"inline-block\",\"margin\":\"0 20px 0 0\",\"padding\":\"0 23px 0 0\",\"fontSize\":24,\"fontWeight\":500,\"verticalAlign\":\"top\",\"lineHeight\":\"49px\"},\"children\":\"404\"}],[\"$\",\"div\",null,{\"style\":{\"display\":\"inline-block\"},\"children\":[\"$\",\"h2\",null,{\"style\":{\"fontSize\":14,\"fontWeight\":400,\"lineHeight\":\"49px\",\"margin\":0},\"children\":\"This page could not be found.\"}]}]]}]}]],\"notFoundStyles\":[],\"styles\":[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/4282badd3d75c77e.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]]}]}]}],null],null],\"couldBeIntercepted\":false,\"initialHead\":[false,\"$L9\"],\"globalErrorComponent\":\"$a\",\"missingSlots\":\"$Wb\"}]]\n"])
        </script>
        <script>
            self.__next_f.push([1, "9:[[\"$\",\"meta\",\"0\",{\"name\":\"viewport\",\"content\":\"width=device-width, initial-scale=1\"}],[\"$\",\"meta\",\"1\",{\"charSet\":\"utf-8\"}],[\"$\",\"title\",\"2\",{\"children\":\"Home\"}],[\"$\",\"meta\",\"3\",{\"name\":\"description\",\"content\":\"Generated by create next app\"}],[\"$\",\"link\",\"4\",{\"rel\":\"icon\",\"href\":\"/favicon.ico\",\"type\":\"image/x-icon\",\"sizes\":\"16x16\"}],[\"$\",\"meta\",\"5\",{\"name\":\"next-size-adjust\"}]]\n5:null\n"])
        </script>
    </body>
</html>
